# Generated by Django 2.1.5 on 2019-02-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190216_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='text',
        ),
    ]
